[pytest]
addopts = --reportportal
rp_endpoint = http://172.30.111.51:30004
rp_api_key = 0bc96aea-164f-4451-8c22-b2a8933951fb
rp_project = superadmin_personal
rp_launch = superadmin_TEST_EXAMPLE
rp_launch_attributes = 
rp_is_skipped_an_issue = False
rp_verify_ssl = True
